CREATE TABLE IF NOT EXISTS `ldapshare_address` (
`address_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`post_id` int(10) unsigned NOT NULL,
`address_title` varchar(255) NOT NULL,
`address_datecreated` datetime NOT NULL,
PRIMARY KEY (`address_id`),
KEY `post_id` (`post_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1000;

CREATE TABLE IF NOT EXISTS `ldapshare_comment` (
`comment_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`post_id` int(10) unsigned NOT NULL,
`user_id` int(10) unsigned NOT NULL,
`comment_content` text NOT NULL,
`comment_httpuseragent` varchar(255) DEFAULT NULL,
`comment_remoteaddr` varchar(255) DEFAULT NULL,
`comment_datecreated` datetime NOT NULL,
PRIMARY KEY (`comment_id`),
KEY `post_id` (`post_id`),
KEY `user_id` (`user_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1000;

CREATE TABLE IF NOT EXISTS `ldapshare_like` (
`like_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`post_id` int(10) unsigned NOT NULL,
`user_id` int(10) unsigned NOT NULL,
`like_datecreated` datetime NOT NULL,
PRIMARY KEY (`like_id`),
KEY `post_id` (`post_id`),
KEY `user_id` (`user_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1000;

CREATE TABLE IF NOT EXISTS `ldapshare_link` (
`link_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`post_id` int(10) unsigned NOT NULL,
`link_url` varchar(255) NOT NULL,
`link_title` varchar(255) NOT NULL,
`link_image` varchar(255) DEFAULT NULL,
`link_video` varchar(255) DEFAULT NULL,
`link_videotype` varchar(255) DEFAULT NULL,
`link_videowidth` int(10) unsigned DEFAULT NULL,
`link_videoheight` int(10) unsigned DEFAULT NULL,
`link_icon` varchar(255) DEFAULT NULL,
`link_description` text,
`link_datecreated` datetime NOT NULL,
PRIMARY KEY (`link_id`),
KEY `post_id` (`post_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1000;

CREATE TABLE IF NOT EXISTS `ldapshare_photo` (
`photo_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`post_id` int(10) unsigned NOT NULL,
`photo_file` varchar(100) NOT NULL,
`photo_datecreated` datetime NOT NULL,
PRIMARY KEY (`photo_id`),
KEY `post_id` (`post_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1000;

CREATE TABLE IF NOT EXISTS `ldapshare_post` (
`post_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`user_id` int(10) unsigned NOT NULL,
`post_content` text NOT NULL,
`post_httpuseragent` varchar(255) DEFAULT NULL,
`post_remoteaddr` varchar(255) DEFAULT NULL,
`post_datecreated` datetime NOT NULL,
PRIMARY KEY (`post_id`),
KEY `user_id` (`user_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1000;

CREATE TABLE IF NOT EXISTS `ldapshare_user` (
`user_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`user_email` varchar(255) NOT NULL,
`user_lastname` varchar(255) NOT NULL,
`user_firstname` varchar(255) NOT NULL,
`user_file` varchar(100) DEFAULT NULL,
`user_token` char(40) DEFAULT NULL,
`user_datecreated` datetime NOT NULL,
PRIMARY KEY (`user_id`),
KEY `user_email` (`user_email`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1000;

INSERT INTO `ldapshare_user` (`user_id`, `user_email`, `user_lastname`, `user_firstname`, `user_file`, `user_token`, `user_datecreated`) VALUES
(1, 'qoh.kkex@example.it', 'Cooper', 'Kaley', NULL, NULL, NOW()),
(2, 'wahtyitw.vrdyp@example.com', 'Davis', 'Stirling', NULL, NULL, NOW()),
(3, 'tppgrkw.bllxdn@example.org', 'Kelly', 'Peg', NULL, NULL, NOW()),
(4, 'fgz.ytattta@example.edu', 'Perez', 'Anthony', NULL, NULL, NOW()),
(5, 'imqefnw.jhujba@example.uk', 'Flores', 'Robynne', NULL, NULL, NOW()),
(6, 'zucxfl.dd@example.fr', 'Clark', 'Deitra', NULL, NULL, NOW()),
(7, 'txkegijf.hbfee@example.it', 'Ramirez', 'Ashlie', NULL, NULL, NOW()),
(8, 'yhaktee.saytx@example.com', 'Evans', 'Keziah', NULL, NULL, NOW()),
(9, 'cvcbhh.mnotvdj@example.org', 'Bailey', 'Victor', NULL, NULL, NOW()),
(10, 'lrasvmuiv.utwravfm@example.edu', 'Brooks', 'Stephania', NULL, NULL, NOW()),
(11, 'yog.hxkohtxlf@example.uk', 'Ross', 'Carine', NULL, NULL, NOW()),
(12, 'ce.vnwf@example.fr', 'Griffin', 'Rain', NULL, NULL, NOW()),
(13, 'dppzftb.zyctx@example.it', 'Hall', 'Perry', NULL, NULL, NOW()),
(14, 'nyzkwvgv.citavc@example.com', 'Scott', 'Melville', NULL, NULL, NOW()),
(15, 'ahvhleup.ivofczpk@example.org', 'Adams', 'Tibby', NULL, NULL, NOW()),
(16, 'wtykex.bpucbboue@example.edu', 'Richardson', 'Noelle', NULL, NULL, NOW()),
(17, 'igoztf.acrufdsql@example.uk', 'Hughes', 'Lucia', NULL, NULL, NOW()),
(18, 'yb.edzwkkwu@example.fr', 'Martin', 'Kennith', NULL, NULL, NOW()),
(19, 'kkaa.csshohg@example.it', 'Gray', 'Fabian', NULL, NULL, NOW()),
(20, 'llhzmi.iwt@example.com', 'Campbell', 'Quincey', NULL, NULL, NOW()),
(21, 'tqoosous.mu@example.org', 'Wood', 'Erick', NULL, NULL, NOW()),
(22, 'vzvr.xbbdgh@example.edu', 'Green', 'Merv', NULL, NULL, NOW()),
(23, 'qbuedhl.luvcj@example.uk', 'Rogers', 'Kory', NULL, NULL, NOW()),
(24, 'uvldqn.bgelodp@example.fr', 'Gonzalez', 'Pierce', NULL, NULL, NOW()),
(25, 'yxupssye.yanesrt@example.it', 'Anderson', 'Hettie', NULL, NULL, NOW()),
(26, 'cumshczu.gqg@example.com', 'Bryant', 'Travis', NULL, NULL, NOW()),
(27, 'xy.kmxm@example.org', 'Parker', 'Merry', NULL, NULL, NOW()),
(28, 'cesducno.gudy@example.edu', 'Martinez', 'Harriet', NULL, NULL, NOW()),
(29, 'krjolh.su@example.uk', 'Watson', 'Tasha', NULL, NULL, NOW()),
(30, 'vsykl.xnhpxx@example.fr', 'Long', 'Ibbie', NULL, NULL, NOW()),
(31, 'essnuufox.scuraur@example.it', 'James', 'Elvis', NULL, NULL, NOW()),
(32, 'nzmt.pgyt@example.com', 'Nelson', 'Faith', NULL, NULL, NOW()),
(33, 'urscqud.zszqyfe@example.org', 'Lee', 'Nicholas', NULL, NULL, NOW()),
(34, 'czr.vbkmouev@example.edu', 'Barnes', 'Kayleah', NULL, NULL, NOW()),
(35, 'svnijob.iaoa@example.uk', 'Allen', 'Jeannine', NULL, NULL, NOW()),
(36, 'cie.muecm@example.fr', 'Foster', 'Rowley', NULL, NULL, NOW()),
(37, 'amqr.logm@example.it', 'Collins', 'Marion', NULL, NULL, NOW()),
(38, 'ablzh.rxtwq@example.com', 'Hernandez', 'Nicole', NULL, NULL, NOW()),
(39, 'vcz.jrqn@example.org', 'Moore', 'Matthias', NULL, NULL, NOW()),
(40, 'tebwzyih.rrbtxqq@example.edu', 'Jackson', 'Hugh', NULL, NULL, NOW()),
(41, 'oich.mghsr@example.uk', 'Henderson', 'Selima', NULL, NULL, NOW()),
(42, 'jiejrn.uzcalwl@example.fr', 'Torres', 'Stanford', NULL, NULL, NOW()),
(43, 'iwbzohlf.wuzuxmyx@example.it', 'Bennett', 'Glenna', NULL, NULL, NOW()),
(44, 'jfwc.uokejho@example.com', 'Smith', 'Carlene', NULL, NULL, NOW()),
(45, 'gsnec.ukaqdod@example.org', 'Stewart', 'Roly', NULL, NULL, NOW()),
(46, 'ekwegdnsr.asb@example.edu', 'Butler', 'Ria', NULL, NULL, NOW()),
(47, 'qqcfyczs.bg@example.uk', 'Cox', 'Ozzie', NULL, NULL, NOW()),
(48, 'ug.ep@example.fr', 'Wilson', 'Wilfrid', NULL, NULL, NOW()),
(49, 'cv.jzdikvr@example.it', 'Carter', 'Kip', NULL, NULL, NOW()),
(50, 'nffqds.rs@example.com', 'Robinson', 'Isador', NULL, NULL, NOW()),
(51, 'gtvio.nidtrnh@example.org', 'Cook', 'Perdita', NULL, NULL, NOW()),
(52, 'or.uumcfvb@example.edu', 'Williams', 'Laurinda', NULL, NULL, NOW()),
(53, 'fjxk.xuwlts@example.uk', 'Jones', 'Karyn', NULL, NULL, NOW()),
(54, 'xztnua.wc@example.fr', 'Gonzales', 'Lonny', NULL, NULL, NOW()),
(55, 'avbuoi.hobak@example.it', 'King', 'Linwood', NULL, NULL, NOW()),
(56, 'eaepmnrt.hihdje@example.com', 'Brown', 'Brett', NULL, NULL, NOW()),
(57, 'cwcdzjv.dr@example.org', 'Harris', 'Barclay', NULL, NULL, NOW()),
(58, 'tuuvbjiu.otjwcyngg@example.edu', 'Thomas', 'Kerenza', NULL, NULL, NOW()),
(59, 'illz.wxcnfh@example.uk', 'Peterson', 'Carter', NULL, NULL, NOW()),
(60, 'sfbrirdjt.uoe@example.fr', 'Simmons', 'Lorrin', NULL, NULL, NOW()),
(61, 'jztyz.ohm@example.it', 'Walker', 'Calanthe', NULL, NULL, NOW()),
(62, 'vpdt.tkmkw@example.com', 'Murphy', 'Reg', NULL, NULL, NOW()),
(63, 'myb.hyiwqxyee@example.org', 'Lopez', 'Jason', NULL, NULL, NOW()),
(64, 'vqtydjsux.xajroymq@example.edu', 'Phillips', 'Lorraine', NULL, NULL, NOW()),
(65, 'ydpc.luxxiseg@example.uk', 'Miller', 'Jasper', NULL, NULL, NOW()),
(66, 'ehi.mwsfdsu@example.fr', 'Morgan', 'Launce', NULL, NULL, NOW()),
(67, 'qvezvbc.cdw@example.it', 'White', 'June', NULL, NULL, NOW()),
(68, 'vhrx.ls@example.com', 'Bell', 'Marcie', NULL, NULL, NOW()),
(69, 'eihtgxtpt.xuwjmgfn@example.org', 'Rivera', 'Madlyn', NULL, NULL, NOW()),
(70, 'rlzoqkf.ukt@example.edu', 'Reed', 'Viola', NULL, NULL, NOW()),
(71, 'ljgm.hax@example.uk', 'Hayes', 'Jenni', NULL, NULL, NOW()),
(72, 'zoyjdv.qzg@example.fr', 'Lewis', 'Alannah', NULL, NULL, NOW()),
(73, 'tllldv.dm@example.it', 'Ward', 'Will', NULL, NULL, NOW()),
(74, 'nvxecvyc.bde@example.com', 'Taylor', 'Earnestine', NULL, NULL, NOW()),
(75, 'reswqthch.dtduld@example.org', 'Roberts', 'Yashmine', NULL, NULL, NOW()),
(76, 'pvbpzmdfb.ypdceu@example.edu', 'Perry', 'Tex', NULL, NULL, NOW()),
(77, 'flxbd.htf@example.uk', 'Garcia', 'Ken', NULL, NULL, NOW()),
(78, 'dx.rzvkofvzz@example.fr', 'Thompson', 'Lloyd', NULL, NULL, NOW()),
(79, 'te.oidos@example.it', 'Powell', 'Terence', NULL, NULL, NOW()),
(80, 'chlelvxdq.eklbjst@example.com', 'Jenkins', 'Robina', NULL, NULL, NOW()),
(81, 'aawlkrlqg.uxvcunpp@example.org', 'Washington', 'Cedric', NULL, NULL, NOW()),
(82, 'wmyz.ub@example.edu', 'Turner', 'Dwayne', NULL, NULL, NOW()),
(83, 'gjqgpeyr.atkingltd@example.uk', 'Young', 'Everett', NULL, NULL, NOW()),
(84, 'vltkmbk.uhraffk@example.fr', 'Wright', 'Samson', NULL, NULL, NOW()),
(85, 'cqvxa.qgjkupgj@example.it', 'Morris', 'Stella', NULL, NULL, NOW()),
(86, 'ph.ts@example.com', 'Price', 'Dave', NULL, NULL, NOW()),
(87, 'aev.wnhrd@example.org', 'Howard', 'Lucasta', NULL, NULL, NOW()),
(88, 'ixy.bpiqqwb@example.edu', 'Mitchell', 'Claudius', NULL, NULL, NOW()),
(89, 'rys.nrhrxq@example.uk', 'Sanders', 'Goodwin', NULL, NULL, NOW()),
(90, 'drvqrkwc.aluq@example.fr', 'Coleman', 'Buck', NULL, NULL, NOW()),
(91, 'frjvx.efheubmjl@example.it', 'Patterson', 'Lavina', NULL, NULL, NOW()),
(92, 'lxglz.nendp@example.com', 'Hill', 'Love', NULL, NULL, NOW()),
(93, 'qvtd.ps@example.org', 'Johnson', 'Derek', NULL, NULL, NOW()),
(94, 'poeoybpg.bofgoe@example.edu', 'Baker', 'Myron', NULL, NULL, NOW()),
(95, 'sl.yxbj@example.uk', 'Edwards', 'Peggy', NULL, NULL, NOW()),
(96, 'ucfk.or@example.fr', 'Sanchez', 'Jay', NULL, NULL, NOW()),
(97, 'whsmxqgg.qedgxc@example.it', 'Rodriguez', 'Basil', NULL, NULL, NOW()),
(98, 'hydb.ucsuf@example.com', 'Alexander', 'Thorley', NULL, NULL, NOW()),
(99, 'clvqx.gvfhy@example.org', 'Russell', 'Iris', NULL, NULL, NOW()),
(100, 'cnx.ufo@example.edu', 'Diaz', 'Ellis', NULL, NULL, NOW());
